name: Setup Flutter
description: Setup your Flutter

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Set Flutter Environment
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true
    - shell: bash
      run: flutter --version

    - name: Get Packages
      shell: bash
      run: flutter pub get
