name: hakondate
description: はこんだて開発用プロジェクト

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.2+11

environment:
  sdk: "3.4.4"
  flutter: "3.22.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # デザイン
  cupertino_icons: 1.0.8
  multi_charts: 0.3.0
  table_calendar: 3.1.2
  flutter_svg: 2.0.10+1
  flutter_pdfview: 1.3.2
  shimmer: 3.0.0
  pin_code_fields: ^8.0.1

  # 状態管理関連
  flutter_riverpod: 2.5.1
  riverpod_annotation: 2.3.5
  freezed: 2.5.2
  freezed_annotation: 2.4.4
  json_serializable: 6.8.0
  json_annotation: 4.9.0

  # Drift(SQLite)関連
  drift: 2.19.1+1
  sqlite3_flutter_libs: 0.5.24

  # 起動時データ関連
  shared_preferences: 2.2.3
  path_provider: 2.1.3
  path: 1.9.0
  intl: 0.19.0

  # 遷移関連
  routemaster: 1.0.1

  # Firebase関連
  app_tracking_transparency: 2.0.5
  firebase_storage: 12.0.0
  firebase_core: 3.0.0
  cloud_firestore: 5.0.0
  firebase_crashlytics: 4.0.0
  firebase_analytics: 11.0.0

  # URL関連
  url_launcher: 6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # コード整形
  very_good_analysis: 6.0.0
  import_sorter: 4.6.0

  # コード生成
  build_runner: 2.4.11
  custom_lint: 0.6.4
  riverpod_generator: 2.4.0
  riverpod_lint: 2.3.10
  drift_dev: 2.19.1
  flutter_oss_licenses: 3.0.2

  # デザイン生成
  flutter_native_splash: 2.4.1
  flutter_launcher_icons: 0.13.1

  # build_runner の実行コマンド
  # flutter packages pub run build_runner build --delete-conflicting-outputs

  # oss_licenses.dart の生成コマンド（パッケージを追加したら実行する）
  # flutter pub run flutter_oss_licenses:generate.dart -o lib/constant/oss_licenses.dart

flutter:
  uses-material-design: true

  assets:
    - assets/debug/
    - assets/slns/json/
    - assets/slns/image/
    - assets/images/
    - assets/images/calendar_hedgehog/
    - assets/images/drawer/
    - assets/images/food_icon/
    - assets/images/information/
    - assets/images/menu_tile/
    - assets/images/label/
    - assets/images/status/
    - assets/images/status/menu_status/
    - assets/initialization_data/
    - assets/loading_animation/
    - assets/svgs/bottom_navigation_bar_icons/

  fonts:
    - family: MPLUSRounded1c
      fonts:
        - asset: fonts/MPLUSRounded1c-Regular.ttf
        - asset: fonts/MPLUSRounded1c-Thin.ttf
          weight: 100
        - asset: fonts/MPLUSRounded1c-Medium.ttf
          weight: 300
        - asset: fonts/MPLUSRounded1c-Light.ttf
          weight: 500
        - asset: fonts/MPLUSRounded1c-Bold.ttf
          weight: 600
        - asset: fonts/MPLUSRounded1c-ExtraBold.ttf
          weight: 800
        - asset: fonts/MPLUSRounded1c-Black.ttf
          weight: 900

flutter_native_splash:
  color: "#FFC966"
  image: assets/images/splash.png
  android: true
  ios: true
  info_plist_files:
    - "ios/Runner/Info-Debug.plist"
    - "ios/Runner/Info-Release.plist"

  # 更新コマンド
  # flutter pub run flutter_native_splash:create

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/icon.png
  adaptive_icon_background: "#FFC966"
  remove_alpha_ios: true

  # 更新コマンド
  # flutter pub run flutter_launcher_icons:main

import_sorter:
  comments: false
  ignored_files:
    - \/lib\/*\/*.freezed.dart
    - \/lib\/*\/*.g.dart
    - \/lib\/*\/oss_licenses.dart
    - \/lib\/*\/firebase_options.dart

  # 実行コマンド
  # flutter pub run import_sorter:main
