name: hakondate
description: はこんだて開発用プロジェクト

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # デザイン
  cupertino_icons: ^1.0.2
  multi_charts: ^0.3.0
  table_calendar: ^3.0.4
  flutter_svg: ^1.0.3

  # 状態管理関連
  flutter_riverpod: ^1.0.4
  freezed_annotation: ^2.0.1
  freezed: ^2.0.1
  json_serializable: ^6.1.6
  json_annotation: ^4.4.0

  # Drift(SQLite)関連
  drift: ^1.0.0
  sqlite3_flutter_libs: ^0.5.0

  # 起動時データ関連
  shared_preferences: ^2.0.7
  path_provider: ^2.0.2
  path: ^1.8.0
  intl: ^0.17.0

  # 遷移関連
  routemaster: ^1.0.0

  # Firebase関連
  firebase_core: ^1.17.0
  cloud_firestore: ^3.1.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.6
  drift_dev: ^1.0.0
  flutter_native_splash: ^1.2.1
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  import_sorter: ^4.6.0
  flutter_oss_licenses: ^2.0.0+1

  # build_runner の実行コマンド
  # flutter packages pub run build_runner build --delete-conflicting-outputs

  # oss_licenses.dart の生成コマンド（パッケージを追加したら実行する）
  # flutter pub run flutter_oss_licenses:generate.dart -o lib/constant/oss_licenses.dart

flutter:

  uses-material-design: true

  assets:
    - assets/debug/
    - assets/slns/
    - assets/images/
    - assets/images/calendar_hedgehog/
    - assets/images/drawer/
    - assets/images/food_icon/
    - assets/images/information/
    - assets/images/menu_tile/
    - assets/images/label/
    - assets/images/menu_status/
    - assets/loading_animation/
    - assets/svgs/bottom_navigation_bar_icons/

  fonts:
    - family: MPLUSRounded1c
      fonts:
        - asset: fonts/MPLUSRounded1c-Regular.ttf
        - asset: fonts/MPLUSRounded1c-Thin.ttf
          weight: 100
        - asset: fonts/MPLUSRounded1c-Medium.ttf
          weight: 300
        - asset: fonts/MPLUSRounded1c-Light.ttf
          weight: 500
        - asset: fonts/MPLUSRounded1c-Bold.ttf
          weight: 600
        - asset: fonts/MPLUSRounded1c-ExtraBold.ttf
          weight: 800
        - asset: fonts/MPLUSRounded1c-Black.ttf
          weight: 900

flutter_native_splash:
  color: "#FFC966"
  image: assets/images/splash.png
  android: true
  ios: true
  info_plist_files:
    - 'ios/Runner/Info-Debug.plist'
    - 'ios/Runner/Info-Release.plist'

  # 更新コマンド
  # flutter pub run flutter_native_splash:create

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/icon.png
  adaptive_icon_background: "#FFC966"
  remove_alpha_ios: true

  # 更新コマンド
  # flutter pub run flutter_launcher_icons:main

import_sorter:
  comments: false
  ignored_files:
    - \/lib\/*\/*.freezed.dart
    - \/lib\/*\/*.g.dart
    - \/lib\/*\/oss_licenses.dart
    - \/lib\/*\/firebase_options.dart

  # 実行コマンド
  # flutter pub run import_sorter:main
