name: Setup Flutter
description: Setup your Flutter

runs:
  using: "composite"
  steps:
    - name: Get Flutter Version From fvm_config.json
      shell: bash
      run: |
        version=$(cat ./.fvmrc | jq -r .flutter)
        echo "FLUTTER_VERSION=${version}" >> $GITHUB_ENV

    - name: Set Flutter Environment
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        cache: true
    - shell: bash
      run: flutter --version

    - name: Get Packages
      shell: bash
      run: flutter pub get
