name: Setup Flutter
description: Setup your Flutter

runs:
  using: "composite"
  steps:
    - name: Get Flutter Version From fvm_config.json
      shell: bash
      run: |
        version=$(cat ./.fvm/fvm_config.json | jq -r .flutterSdkVersion)
        echo "FLUTTER_VERSION=${version}" >> $GITHUB_ENV

    - name: Set Flutter Environment
      uses: subosito/flutter-action@v2
      with:
        channel: $FLUTTER_VERSION
        cache: true
    - shell: bash
      run: |
        git config --global --add safe.directory /opt/hostedtoolcache/flutter/${{ steps.flutter-action.outputs.CHANNEL }}-${{ steps.flutter-action.outputs.VERSION }}-${{ steps.flutter-action.outputs.ARCHITECTURE }}
        flutter --version
    - shell: bash
      run: flutter --version

    - name: Get Packages
      shell: bash
      run: flutter pub get
