name: Check Lint

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:  
  run-linter:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter
      
      - name: Run Flutter Format
        run: dart format --set-exit-if-changed -o none -l 140 $(find lib -name "*.dart" -not -wholename "**/*.g*" -not -wholename "**/*.freezed.*" -not -wholename "**/firebase_options.dart" -not -wholename "**/oss_licenses.dart")      

      - name: Run Flutter Analyzer
        run: flutter analyze
        
      - name: Run Custom Linter
        run: flutter pub run custom_lint
