name: check lint

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: 'Setup flutter environment'
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
        
      - name: 'Get packages'
        run: flutter pub get

      - name: 'Check lint'
        run: flutter analyze
