name: run build_runner

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter pub run flutter_oss_licenses:generate.dart -o lib/constant/oss_licenses.dart
      - run: flutter pub run import_sorter:main
