name: run build_runner

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: 'Setup flutter environment'
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
        
      - name: 'Get packages'
        run: flutter pub get
        
      - name: 'Run flutter_oss_licenses'
        run: flutter pub run flutter_oss_licenses:generate.dart -o lib/constant/oss_licenses.dart
      
      - name: 'Run import_sorter'
        run: flutter pub run import_sorter:main

      - name: 'Commit and push changes'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          if (git diff --shortstat | grep '[0-9]'); then \
            git add .; \
            git commit -m '[refactor]Ran OSS Licenses generator and import sorter'; \
            git config pull.rebase false; \
            git pull origin ${{github.head_ref}}; \
            git push origin ${{github.head_ref}}; \
          fi
